language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t shadzic/docker-react -f Dockerfile.dev . #initial image

script:
  - docker run -e CI=true shadzic/docker-react npm run test -- --coverage #run tests

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-333268614004"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY" # configured in Travis CI
    secure: "$AWS_SECRET_KEY"